# Server Configuration 
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/futeboldb
spring.datasource.username=postgres
spring.datasource.password=elaia
spring.jpa.hibernate.ddl-auto=update